-- 코드를 입력하세요
# SELECT M.MEMBER_NAME, A.REVIEW_TEXT, A.REVIEW_DATE
# FROM (
#     SELECT MEMBER_ID, COUNT (MEMBER_ID) CNT, REVIEW_TEXT, DATE_FORMAT(REVIEW_DATE, '%Y-%m-%d') REVIEW_DATE
#     FROM REST_REVIEW
#     GROUP BY MEMBER_ID
#     ORDER BY CNT DESC
#     LIMIT 1
# ) A JOIN MEMBER_PROFILE M ON A.MEMBER_ID = M.MEMBER_ID
# WHERE 

SELECT M.MEMBER_NAME, B.REVIEW_TEXT, B.REVIEW_DATE
FROM MEMBER_PROFILE M JOIN (
    SELECT R.MEMBER_ID, R.REVIEW_TEXT, DATE_FORMAT(R.REVIEW_DATE, '%Y-%m-%d') REVIEW_DATE
    FROM REST_REVIEW R JOIN ( 
        SELECT MEMBER_ID, COUNT(MEMBER_ID) CNT
        FROM REST_REVIEW
        GROUP BY MEMBER_ID
        ORDER BY CNT DESC
        LIMIT 1) A ON R.MEMBER_ID = A.MEMBER_ID
) B ON M.MEMBER_ID = B.MEMBER_ID
ORDER BY REVIEW_DATE, REVIEW_TEXT